music.setVolume(90)
music.setTempo(130)
music.playTone(277, music.beat(BeatFraction.Whole))
music.playTone(330, music.beat(BeatFraction.Half))
music.playTone(277, music.beat(BeatFraction.Half))
music.playTone(330, music.beat(BeatFraction.Half))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Half))
music.playTone(330, music.beat(BeatFraction.Half))
music.playTone(330, music.beat(BeatFraction.Eighth))
music.rest(music.beat(BeatFraction.Eighth))
music.playTone(370, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Double))
music.playTone(277, music.beat(BeatFraction.Whole))
music.playTone(330, music.beat(BeatFraction.Half))
music.playTone(277, music.beat(BeatFraction.Half))
music.playTone(330, music.beat(BeatFraction.Half))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Half))
music.playTone(330, music.beat(BeatFraction.Half))
music.playTone(330, music.beat(BeatFraction.Eighth))
music.rest(music.beat(BeatFraction.Eighth))
music.playTone(370, music.beat(BeatFraction.Whole))
music.playTone(330, music.beat(BeatFraction.Whole))
music.playTone(277, music.beat(BeatFraction.Whole))
